drop view  Votes;

drop table Comments;
drop table Assumptions;
drop table POI;
drop table Images;
drop table Objects;
drop table Users;

create table Users (
	uid      int          primary key generated by default as identity,
	uname    varchar(32)  not null    unique,
	password varchar(64)  not null,
	joined   timestamp    not null
);

create table Objects (
	oid         int           primary key generated by default as identity,
	uid         int           not null    references Users (uid),
	label       varchar(256)  not null    unique,
	description varchar(4096),
	latitude    float,
	longitude   float
);

create table Images (
	iid         int           primary key generated by default as identity,
	uid         int           not null    references Users  (uid),
	filename    varchar(64)   not null    unique,
	description varchar(4096),
	added       timestamp     not null,
	taken_from  int                       references Objects(oid)
	-- FIXME: radius
	-- FIXME: taken timestamp nullable;
	-- FIXME: taken_from as assumption
);

create table POI (
	pid int          primary key generated by default as identity,
	iid int   not null references Images(iid),
	uid int   not null references Users (uid),
	x   float not null,
	y   float not null
);

create table Assumptions (
	aid   int       primary key generated by default as identity,
	pid   int       not null    references POI    (pid),
	oid   int       not null    references Objects(oid),
	uid   int       not null    references Users  (uid),
	added timestamp not null
);

create table Comments (
	cid   int           primary key generated by default as identity,
	aid   int           not null    references Assumptions (aid),
	uid   int           not null    references Users       (uid),
	text  varchar(2048),
	added timestamp     not null,
	vote  int           not null -- FIXME: constraint to {-1,0,+1}
);

create view Votes as
select
	A.*,
	(select coalesce(sum(vote),0) from Comments as C where C.aid = A.aid) as votes
from Assumptions as A;
